GET HTTP://localhost:9000/

###
GET HTTP://localhost:9000/permit

###
POST HTTP://localhost:9000/permit
Content-Type: application/json

{
    "email_address": "newest@gmail.com",
    "password": "goodlord123"
}

###
POST HTTP://localhost:9000/permit/
Content-Type: application/json

{
    "email_address": "deletionTesting@gmail.com",
    "password": "asdf1234"
}
###
POST HTTP://localhost:9000/permit/login
Content-Type: application/json

{
    "email_address": "deletionTesting@gmail.com",
    "password": "asdf1234"
}
###
DELETE HTTP://localhost:9000/permit/login
Content-Type: application/json

{
    "email_address": "deletionTesting@gmail.com",
    "password": "asdf1234"
}

###
POST HTTP://localhost:9000/permit/login
Content-Type: application/json

{
    "email_address": "creationTesting@gmail.de",
    "password": "a&+_/asdfb4"
}

###
POST HTTP://localhost:9000/permit/login
Content-Type: application/json

{
    "email_address": "hotmail111@hotmail.com",
    "password": "counting1234"
}


###
POST HTTP://localhost:9000/permit/login
Content-Type: application/json

{
    "email_address": "hotmail@hotmail.com",
    "password": "asdf1234"
}

###

POST HTTP://localhost:9000/permit/login 
Content-Type: application/json

{
    "email_address": "hotmail@hotmail.com",
    "password": "asdf12345"
}

###
GET HTTP://localhost:9000/creation

###
GET HTTP://localhost:9000/forest

###
GET HTTP://localhost:9000/deforested

###

GET HTTP://localhost:9000/forest/647f436a95895a0118631999
###

POST HTTP://localhost:9000/forest/647f436a95895a0118631999
Content-Type: application/json

{
    "purpose": "c_info",
    "email": "hotmail@hotmail.com",
    "password": "asdf12345"
}

### 

GET http://localhost:9000/the-dam/transaction/65467cc8d106994bac5d6319

### 

POST http://localhost:9000/the-dam/transaction/655c0a5007b8d4b3dcb17d16
Content-Type: application/json

{
    "company": "Tech Company",
    "transType": "Wages",
    "dolValue": 957
}

### 

GET http://localhost:9000/the-dam/transaction/6578e24d16597888ec82232f

### 

GET http://localhost:9000/the-dam/creation/6578e24d16597888ec82232f

### 

GET http://localhost:9000/the-dam/transaction/

###
POST HTTP://localhost:9000/permit/login
Content-Type: application/json

{
    "email_address": "newest@gmail.com",
    "password": "goodlord123"
}









